#!/bin/bash

INSTANCE_DIR=$(dirname -- "${BASH_SOURCE[0]}")

set -o allexport
source $INSTANCE_DIR/.env
if test -f "$INSTANCE_DIR/.env.local"; then
    source $INSTANCE_DIR/.env.local
fi
set +o allexport

pushd $INSTANCE_DIR/../../takahe
source venv/bin/activate

gunicorn takahe.wsgi:application --workers 1 --bind 0.0.0.0:5060
